/* The following code was generated by JFlex 1.6.1 */

/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").  
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2008, 2016, Oracle and/or its affiliates. All rights reserved.
 */

/*
 * Cross reference a C++ file
 */

package org.opensolaris.opengrok.analysis.c;
import org.opensolaris.opengrok.analysis.JFlexXref;
import java.io.IOException;
import java.io.Writer;
import java.io.Reader;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.opensolaris.opengrok.web.Util;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/myworld/github/OpenGrok/src/org/opensolaris/opengrok/analysis/c/CxxXref.lex</tt>
 */
public class CxxXref extends JFlexXref {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;
  public static final int SCOMMENT = 6;
  public static final int QSTRING = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\0\1\1\1\2\22\0\1\1\1\6\1\52"+
    "\1\47\2\6\1\56\1\53\2\57\1\54\1\33\1\6\1\10\1\11"+
    "\1\37\1\40\11\5\1\62\1\46\1\50\1\6\1\51\1\6\1\63"+
    "\1\21\1\41\1\13\1\34\1\42\1\17\1\4\1\24\1\36\1\20"+
    "\1\4\1\32\1\31\1\16\1\15\1\23\2\4\1\61\1\26\1\43"+
    "\1\22\1\4\1\30\2\4\1\57\1\55\2\57\1\7\1\57\1\21"+
    "\1\41\1\14\1\34\1\42\1\17\1\4\1\25\1\36\1\20\1\4"+
    "\1\32\1\31\1\16\1\15\1\23\2\4\1\12\1\27\1\43\1\22"+
    "\1\4\1\30\2\4\1\44\1\57\1\45\1\6\261\0\2\35\115\0"+
    "\1\60\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ufe90\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\2\3\1\4\1\5\3\4\1\6"+
    "\1\7\1\10\1\4\1\11\1\12\1\13\1\14\1\15"+
    "\5\4\1\16\2\4\1\2\2\17\1\20\1\4\1\21"+
    "\1\0\1\5\1\0\1\22\1\23\15\0\1\24\1\25"+
    "\1\26\1\0\1\27\2\5\1\0\1\5\1\0\1\30"+
    "\1\0\1\30\3\0\1\30\1\0\1\30\6\0\1\2"+
    "\1\5\14\0\1\31\5\0\1\30\2\0\1\30\1\0"+
    "\1\32\10\0\1\33\12\0\1\34\37\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\u016c"+
    "\0\u0104\0\u01a0\0\u01d4\0\u0104\0\u0208\0\u023c\0\u0104\0\u0104"+
    "\0\u0104\0\u0270\0\u0104\0\u0104\0\u0104\0\u0104\0\u0104\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u0104\0\u04ac\0\u04e0\0\u01a0\0\u0514\0\u0548\0\u057c"+
    "\0\u0104\0\u0104\0\u05b0\0\u05e4\0\u0270\0\u0618\0\u02a4\0\u064c"+
    "\0\u0680\0\u06b4\0\u02d8\0\u06e8\0\u071c\0\u0750\0\u0784\0\u0104"+
    "\0\u0104\0\u0104\0\u07b8\0\u0104\0\u07ec\0\u0820\0\u0854\0\u0888"+
    "\0\u08bc\0\u02a4\0\u08f0\0\u08f0\0\u0924\0\u0958\0\u098c\0\u098c"+
    "\0\u09c0\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8"+
    "\0\u0104\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64"+
    "\0\u0c98\0\u0ccc\0\u0d00\0\u0d34\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04"+
    "\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\u0104\0\u0f08\0\u0f3c\0\u0d34"+
    "\0\u0f70\0\u0e04\0\u0fa4\0\u0fd8\0\u100c\0\u1040\0\u1074\0\u10a8"+
    "\0\u10dc\0\u1110\0\u10dc\0\u1144\0\u1178\0\u11ac\0\u11e0\0\u1214"+
    "\0\u1248\0\u127c\0\u12b0\0\u12e4\0\u1318\0\u0104\0\u134c\0\u1380"+
    "\0\u13b4\0\u13e8\0\u141c\0\u1450\0\u1484\0\u14b8\0\u14ec\0\u1520"+
    "\0\u1554\0\u1588\0\u15bc\0\u15f0\0\u1624\0\u1658\0\u168c\0\u16c0"+
    "\0\u16f4\0\u1728\0\u175c\0\u1790\0\u17c4\0\u17f8\0\u182c\0\u1860"+
    "\0\u1894\0\u18c8\0\u18fc\0\u1930\0\u1964";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\12"+
    "\2\14\21\12\1\14\1\12\1\6\1\12\1\15\1\16"+
    "\3\12\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\2\14\1\27\1\14\1\6\1\12\2\14\1\6"+
    "\1\7\1\10\1\11\1\30\1\31\1\14\3\31\5\30"+
    "\1\32\4\30\2\33\5\30\1\14\1\30\1\6\1\30"+
    "\1\34\1\31\3\30\4\14\1\23\1\24\1\35\2\14"+
    "\1\36\1\27\1\14\1\6\1\30\2\14\1\6\1\7"+
    "\1\10\1\11\1\30\1\31\1\14\3\31\5\30\1\32"+
    "\4\30\2\33\5\30\1\14\1\30\1\6\1\30\1\34"+
    "\1\31\3\30\4\14\1\23\1\24\2\14\1\37\1\14"+
    "\1\27\1\14\1\6\1\30\2\14\1\6\1\40\1\41"+
    "\1\42\1\30\1\31\1\14\3\31\5\30\1\32\4\30"+
    "\2\33\5\30\1\14\1\30\1\6\1\30\1\34\1\31"+
    "\3\30\4\14\1\23\1\24\4\14\1\27\1\14\1\6"+
    "\1\30\2\14\1\6\1\7\1\10\1\11\1\30\1\31"+
    "\1\14\3\31\5\30\1\32\4\30\2\33\5\30\1\14"+
    "\1\30\1\6\1\30\1\34\1\31\3\30\4\14\1\23"+
    "\1\24\1\14\1\43\1\14\1\44\1\27\1\14\1\6"+
    "\1\30\2\14\65\0\1\7\1\10\1\11\63\0\1\11"+
    "\64\0\2\45\1\0\1\45\2\0\21\45\1\0\1\45"+
    "\1\0\1\45\1\0\4\45\15\0\1\45\7\0\1\13"+
    "\3\0\1\46\5\0\1\47\12\0\1\47\1\0\1\47"+
    "\3\0\1\13\1\0\1\50\1\47\57\0\1\51\14\0"+
    "\1\52\14\0\1\53\3\0\1\46\16\0\1\54\7\0"+
    "\1\53\24\0\1\55\33\0\2\56\31\0\2\57\1\0"+
    "\2\57\1\60\21\57\1\0\1\57\1\0\1\57\1\61"+
    "\4\57\15\0\1\57\1\0\1\62\4\0\2\63\1\0"+
    "\24\63\1\0\1\63\1\0\1\63\1\0\4\63\15\0"+
    "\1\63\1\0\1\62\4\0\2\57\1\0\2\57\1\60"+
    "\14\57\2\64\3\57\1\0\1\57\1\0\1\57\1\61"+
    "\4\57\15\0\1\57\1\0\1\62\4\0\2\57\1\0"+
    "\2\57\1\60\14\57\2\65\3\57\1\0\1\57\1\0"+
    "\1\57\1\61\4\57\15\0\1\57\1\0\1\62\4\0"+
    "\1\66\5\0\21\66\1\0\1\66\1\0\1\66\2\0"+
    "\3\66\15\0\1\66\3\0\1\67\134\0\1\70\2\0"+
    "\1\71\45\0\1\72\25\0\1\40\1\41\1\42\63\0"+
    "\1\42\61\0\1\73\135\0\1\74\1\0\1\71\13\0"+
    "\1\75\32\0\1\75\42\0\1\47\12\0\1\47\1\0"+
    "\1\47\6\0\1\47\25\0\1\76\2\0\1\77\22\0"+
    "\1\77\4\0\1\76\30\0\1\53\3\0\1\46\26\0"+
    "\1\53\30\0\1\100\5\0\2\100\2\0\1\100\1\0"+
    "\1\100\12\0\1\100\3\0\3\100\37\0\1\101\51\0"+
    "\2\57\1\0\2\57\1\60\1\102\1\103\1\104\3\57"+
    "\1\105\2\57\1\106\1\107\1\110\1\111\1\112\1\113"+
    "\2\57\1\0\1\114\1\0\1\57\1\61\4\57\15\0"+
    "\1\57\1\0\1\62\4\0\1\115\5\0\21\115\1\0"+
    "\1\115\1\0\1\115\2\0\3\115\15\0\1\115\6\0"+
    "\2\116\1\0\24\116\1\0\1\116\1\0\1\116\1\0"+
    "\4\116\15\0\1\116\6\0\2\57\1\0\2\57\1\60"+
    "\11\57\1\117\7\57\1\0\1\57\1\0\1\57\1\61"+
    "\4\57\15\0\1\57\1\0\1\62\4\0\2\57\1\0"+
    "\2\57\1\60\14\57\2\120\3\57\1\0\1\57\1\0"+
    "\1\57\1\61\4\57\15\0\1\57\1\0\1\62\4\0"+
    "\2\66\1\0\24\66\1\0\1\66\1\0\1\66\1\61"+
    "\4\66\15\0\1\66\3\0\1\67\50\0\1\121\12\0"+
    "\1\73\51\0\1\121\15\0\1\75\11\0\1\47\12\0"+
    "\1\47\1\0\1\47\3\0\1\75\1\0\1\50\1\47"+
    "\25\0\1\76\11\0\1\47\12\0\1\47\1\0\1\47"+
    "\3\0\1\76\2\0\1\47\25\0\1\76\32\0\1\76"+
    "\30\0\1\100\5\0\2\100\2\0\1\100\1\0\1\100"+
    "\10\0\1\47\1\0\1\100\3\0\2\100\1\122\1\47"+
    "\33\0\2\123\53\0\2\57\1\0\2\57\1\60\1\57"+
    "\2\102\1\124\5\57\1\125\4\57\1\126\2\57\1\127"+
    "\1\57\1\0\1\57\1\61\4\57\15\0\1\57\1\0"+
    "\1\62\4\0\2\57\1\0\2\57\1\60\7\57\1\130"+
    "\11\57\1\0\1\57\1\0\1\57\1\61\4\57\15\0"+
    "\1\57\1\0\1\62\4\0\2\57\1\0\2\57\1\60"+
    "\7\57\1\131\10\57\1\102\1\0\1\57\1\0\1\57"+
    "\1\61\4\57\15\0\1\57\1\0\1\62\4\0\2\57"+
    "\1\0\2\57\1\60\11\57\1\125\2\102\2\132\1\126"+
    "\2\57\1\127\1\57\1\0\1\57\1\61\4\57\15\0"+
    "\1\57\1\0\1\62\4\0\2\57\1\0\2\57\1\60"+
    "\16\57\1\133\2\57\1\0\1\57\1\0\1\57\1\61"+
    "\4\57\15\0\1\57\1\0\1\62\4\0\2\57\1\0"+
    "\2\57\1\60\17\57\1\134\1\57\1\0\1\57\1\0"+
    "\1\57\1\61\4\57\15\0\1\57\1\0\1\62\4\0"+
    "\2\57\1\0\2\57\1\60\21\57\1\0\1\57\1\135"+
    "\1\136\1\61\4\57\15\0\1\57\1\0\1\62\4\0"+
    "\2\137\1\0\3\115\21\137\1\0\1\137\1\0\1\137"+
    "\1\0\4\137\15\0\1\137\6\0\2\116\1\0\2\116"+
    "\1\140\21\116\1\0\1\116\1\0\1\116\1\0\4\116"+
    "\15\0\1\116\6\0\2\57\1\0\2\57\1\60\21\57"+
    "\1\0\1\57\1\0\1\57\1\61\4\57\15\0\1\57"+
    "\1\141\1\62\4\0\2\57\1\0\2\57\1\60\11\57"+
    "\1\142\7\57\1\0\1\57\1\0\1\57\1\61\4\57"+
    "\15\0\1\57\1\0\1\62\5\0\1\100\2\0\1\77"+
    "\2\0\2\100\2\0\1\100\1\0\1\100\10\0\1\47"+
    "\1\77\1\100\3\0\2\100\1\122\1\47\52\0\1\143"+
    "\35\0\2\57\1\0\2\57\1\60\4\57\1\144\14\57"+
    "\1\0\1\57\1\0\1\57\1\61\4\57\15\0\1\57"+
    "\1\0\1\62\4\0\2\57\1\0\2\57\1\60\11\57"+
    "\1\102\7\57\1\0\1\57\1\0\1\57\1\61\4\57"+
    "\15\0\1\57\1\0\1\62\4\0\2\57\1\0\2\57"+
    "\1\60\16\57\1\102\2\57\1\0\1\57\1\0\1\57"+
    "\1\61\4\57\15\0\1\57\1\0\1\62\33\0\1\145"+
    "\34\0\2\57\1\0\2\57\1\60\10\57\1\146\10\57"+
    "\1\0\1\57\1\0\1\57\1\61\4\57\15\0\1\57"+
    "\1\0\1\62\4\0\2\57\1\0\2\57\1\60\14\57"+
    "\2\147\3\57\1\0\1\57\1\0\1\57\1\61\4\57"+
    "\15\0\1\57\1\0\1\62\4\0\2\57\1\0\2\57"+
    "\1\60\17\57\1\150\1\57\1\0\1\57\1\0\1\57"+
    "\1\61\4\57\15\0\1\57\1\0\1\62\4\0\2\57"+
    "\1\0\2\57\1\60\14\57\2\102\3\57\1\0\1\57"+
    "\1\0\1\57\1\61\4\57\15\0\1\57\1\0\1\62"+
    "\4\0\2\57\1\0\2\57\1\60\20\57\1\102\1\0"+
    "\1\57\1\0\1\57\1\61\4\57\15\0\1\57\1\0"+
    "\1\62\17\0\1\151\50\0\2\57\1\0\2\57\1\60"+
    "\5\57\1\144\13\57\1\0\1\57\1\0\1\57\1\61"+
    "\4\57\15\0\1\57\1\0\1\62\4\0\2\137\1\0"+
    "\3\115\21\137\1\0\1\137\1\0\1\137\1\61\4\137"+
    "\15\0\1\137\6\0\2\152\1\0\24\152\1\0\1\152"+
    "\1\0\1\152\1\0\4\152\15\0\1\152\41\0\1\153"+
    "\30\0\2\57\1\0\2\57\1\60\1\117\20\57\1\0"+
    "\1\57\1\0\1\57\1\61\4\57\14\0\1\154\1\117"+
    "\1\141\1\62\43\0\1\155\24\0\2\57\1\0\2\57"+
    "\1\60\5\57\1\102\13\57\1\0\1\57\1\0\1\57"+
    "\1\61\4\57\15\0\1\57\1\0\1\62\4\0\2\57"+
    "\1\0\2\57\1\60\7\57\1\102\11\57\1\0\1\57"+
    "\1\0\1\57\1\61\4\57\15\0\1\57\1\0\1\62"+
    "\4\0\2\57\1\0\2\57\1\60\1\57\2\156\16\57"+
    "\1\0\1\57\1\0\1\57\1\61\4\57\15\0\1\57"+
    "\1\0\1\62\17\0\1\145\103\0\1\157\106\0\1\141"+
    "\35\0\1\160\33\0\2\57\1\0\2\57\1\60\12\57"+
    "\2\102\5\57\1\0\1\57\1\0\1\57\1\61\4\57"+
    "\15\0\1\57\1\0\1\62\4\0\31\161\1\0\6\161"+
    "\2\0\1\161\5\0\3\161\2\0\3\161\42\0\1\162"+
    "\25\0\2\163\4\161\21\163\1\161\1\163\1\0\6\163"+
    "\2\0\1\161\5\0\3\161\2\0\1\163\2\161\1\0"+
    "\1\162\46\0\1\164\17\0\1\165\2\0\1\166\2\0"+
    "\21\165\1\0\1\165\1\0\1\165\1\167\1\0\3\165"+
    "\15\0\1\165\6\0\2\170\1\0\1\170\1\171\1\172"+
    "\21\170\1\0\1\170\1\0\1\170\1\173\4\170\15\0"+
    "\1\170\6\0\2\174\1\0\1\174\2\0\21\174\1\0"+
    "\1\174\1\0\1\174\1\0\4\174\15\0\1\174\6\0"+
    "\1\175\5\0\21\175\1\0\1\175\1\0\1\175\2\0"+
    "\3\175\15\0\1\175\6\0\2\170\1\0\1\170\1\171"+
    "\1\172\21\170\1\0\1\170\1\0\1\170\1\173\4\170"+
    "\5\0\1\176\7\0\1\170\6\0\2\171\1\0\2\171"+
    "\1\172\21\171\1\0\1\171\1\0\1\171\1\173\4\171"+
    "\15\0\1\171\6\0\2\171\1\0\2\171\1\172\1\177"+
    "\1\200\1\201\3\171\1\202\2\171\1\203\1\204\1\205"+
    "\1\206\1\207\1\210\2\171\1\0\1\211\1\0\1\171"+
    "\1\173\4\171\15\0\1\171\6\0\1\212\5\0\21\212"+
    "\1\0\1\212\1\0\1\212\2\0\3\212\15\0\1\212"+
    "\6\0\2\174\1\0\1\174\2\0\21\174\1\0\1\174"+
    "\1\0\1\174\1\0\4\174\5\0\1\176\7\0\1\174"+
    "\6\0\2\175\1\0\24\175\1\0\1\175\1\0\1\175"+
    "\1\173\4\175\15\0\1\175\6\0\2\171\1\0\2\171"+
    "\1\172\21\171\1\0\1\171\1\0\1\171\1\173\4\171"+
    "\5\0\1\176\7\0\1\171\6\0\2\171\1\0\2\171"+
    "\1\172\1\171\2\177\1\213\5\171\1\214\4\171\1\215"+
    "\2\171\1\216\1\171\1\0\1\171\1\173\4\171\15\0"+
    "\1\171\6\0\2\171\1\0\2\171\1\172\1\171\2\177"+
    "\1\213\5\171\1\214\4\171\1\215\2\171\1\216\1\171"+
    "\1\0\1\171\1\173\4\171\5\0\1\176\7\0\1\171"+
    "\6\0\2\171\1\0\2\171\1\172\7\171\1\217\11\171"+
    "\1\0\1\171\1\0\1\171\1\173\4\171\15\0\1\171"+
    "\6\0\2\171\1\0\2\171\1\172\7\171\1\220\10\171"+
    "\1\177\1\0\1\171\1\0\1\171\1\173\4\171\15\0"+
    "\1\171\6\0\2\171\1\0\2\171\1\172\11\171\1\214"+
    "\2\177\2\221\1\215\2\171\1\216\1\171\1\0\1\171"+
    "\1\173\4\171\15\0\1\171\6\0\2\171\1\0\2\171"+
    "\1\172\11\171\1\214\2\177\2\221\1\215\2\171\1\216"+
    "\1\171\1\0\1\171\1\173\4\171\5\0\1\176\7\0"+
    "\1\171\6\0\2\171\1\0\2\171\1\172\16\171\1\222"+
    "\2\171\1\0\1\171\1\0\1\171\1\173\4\171\15\0"+
    "\1\171\6\0\2\171\1\0\2\171\1\172\16\171\1\222"+
    "\2\171\1\0\1\171\1\0\1\171\1\173\4\171\5\0"+
    "\1\176\7\0\1\171\6\0\2\171\1\0\2\171\1\172"+
    "\17\171\1\223\1\171\1\0\1\171\1\0\1\171\1\173"+
    "\4\171\15\0\1\171\6\0\2\171\1\0\2\171\1\172"+
    "\21\171\1\0\1\171\1\224\1\225\1\173\4\171\15\0"+
    "\1\171\6\0\2\226\1\0\3\212\21\226\1\0\1\226"+
    "\1\0\1\226\1\0\4\226\15\0\1\226\6\0\2\171"+
    "\1\0\2\171\1\172\4\171\1\227\14\171\1\0\1\171"+
    "\1\0\1\171\1\173\4\171\15\0\1\171\6\0\2\171"+
    "\1\0\2\171\1\172\11\171\1\177\7\171\1\0\1\171"+
    "\1\0\1\171\1\173\4\171\15\0\1\171\6\0\2\171"+
    "\1\0\2\171\1\172\16\171\1\177\2\171\1\0\1\171"+
    "\1\0\1\171\1\173\4\171\15\0\1\171\35\0\1\230"+
    "\34\0\2\171\1\0\2\171\1\172\10\171\1\231\10\171"+
    "\1\0\1\171\1\0\1\171\1\173\4\171\15\0\1\171"+
    "\6\0\2\171\1\0\2\171\1\172\14\171\2\232\3\171"+
    "\1\0\1\171\1\0\1\171\1\173\4\171\15\0\1\171"+
    "\6\0\2\171\1\0\2\171\1\172\17\171\1\233\1\171"+
    "\1\0\1\171\1\0\1\171\1\173\4\171\15\0\1\171"+
    "\6\0\2\171\1\0\2\171\1\172\14\171\2\177\3\171"+
    "\1\0\1\171\1\0\1\171\1\173\4\171\15\0\1\171"+
    "\6\0\2\171\1\0\2\171\1\172\20\171\1\177\1\0"+
    "\1\171\1\0\1\171\1\173\4\171\15\0\1\171\21\0"+
    "\1\234\50\0\2\171\1\0\2\171\1\172\5\171\1\227"+
    "\13\171\1\0\1\171\1\0\1\171\1\173\4\171\15\0"+
    "\1\171\6\0\2\226\1\0\3\212\21\226\1\0\1\226"+
    "\1\0\1\226\1\173\4\226\5\0\1\176\7\0\1\226"+
    "\6\0\2\171\1\0\2\171\1\172\5\171\1\177\13\171"+
    "\1\0\1\171\1\0\1\171\1\173\4\171\15\0\1\171"+
    "\53\0\1\176\16\0\2\171\1\0\2\171\1\172\7\171"+
    "\1\177\11\171\1\0\1\171\1\0\1\171\1\173\4\171"+
    "\15\0\1\171\6\0\2\171\1\0\2\171\1\172\1\171"+
    "\2\235\16\171\1\0\1\171\1\0\1\171\1\173\4\171"+
    "\15\0\1\171\6\0\2\171\1\0\2\171\1\172\20\171"+
    "\1\177\1\0\1\171\1\0\1\171\1\173\4\171\5\0"+
    "\1\176\7\0\1\171\21\0\1\230\50\0\2\171\1\0"+
    "\2\171\1\172\12\171\2\177\5\171\1\0\1\171\1\0"+
    "\1\171\1\173\4\171\15\0\1\171\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6552];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\2\1\1\11\2\1\1\11\2\1\3\11"+
    "\1\1\5\11\12\1\1\11\3\1\1\0\1\1\1\0"+
    "\2\11\15\0\3\11\1\0\1\11\2\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\3\0\1\1\1\0\1\1"+
    "\6\0\1\11\1\1\14\0\1\1\5\0\1\11\2\0"+
    "\1\1\1\0\1\1\10\0\1\1\12\0\1\11\37\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  // TODO move this into an include file when bug #16053 is fixed
  @Override
  protected int getLineNumber() { return yyline; }
  @Override
  protected void setLineNumber(int x) { yyline = x; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CxxXref(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 216) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { writeUnicodeChar(yycharat(0));
            }
          case 29: break;
          case 2: 
            { out.write(yytext());
            }
          case 30: break;
          case 3: 
            { startNewLine();
            }
          case 31: break;
          case 4: 
            { out.write(yycharat(0));
            }
          case 32: break;
          case 5: 
            { out.write("<span class=\"n\">"); out.write(yytext()); out.write("</span>");
            }
          case 33: break;
          case 6: 
            { incScope(); writeUnicodeChar(yycharat(0));
            }
          case 34: break;
          case 7: 
            { decScope(); writeUnicodeChar(yycharat(0));
            }
          case 35: break;
          case 8: 
            { endScope(); writeUnicodeChar(yycharat(0));
            }
          case 36: break;
          case 9: 
            { out.write( "&lt;");
            }
          case 37: break;
          case 10: 
            { out.write( "&gt;");
            }
          case 38: break;
          case 11: 
            { yybegin(STRING);out.write("<span class=\"s\">\"");
            }
          case 39: break;
          case 12: 
            { yybegin(QSTRING);out.write("<span class=\"s\">\'");
            }
          case 40: break;
          case 13: 
            { out.write( "&amp;");
            }
          case 41: break;
          case 14: 
            { yybegin(YYINITIAL); out.write("\"</span>");
            }
          case 42: break;
          case 15: 
            { yybegin(YYINITIAL); out.write("</span>");
                  startNewLine();
            }
          case 43: break;
          case 16: 
            { yybegin(YYINITIAL); out.write("'</span>");
            }
          case 44: break;
          case 17: 
            { String id = yytext();
    writeSymbol(id, CxxConsts.kwd, yyline);
            }
          case 45: break;
          case 18: 
            { yybegin(SCOMMENT);out.write("<span class=\"c\">//");
            }
          case 46: break;
          case 19: 
            { yybegin(COMMENT);out.write("<span class=\"c\">/*");
            }
          case 47: break;
          case 20: 
            { out.write("\\\"");
            }
          case 48: break;
          case 21: 
            { out.write("\\\\");
            }
          case 49: break;
          case 22: 
            { yybegin(YYINITIAL); out.write("*/</span>");
            }
          case 50: break;
          case 23: 
            { out.write("\\\'");
            }
          case 51: break;
          case 24: 
            { String path = yytext();
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
            }
          case 52: break;
          case 25: 
            { out.write(Util.breadcrumbPath(urlPrefix+"path=",yytext(),'/'));
            }
          case 53: break;
          case 26: 
            { writeEMailAddress(yytext());
            }
          case 54: break;
          case 27: 
            { appendLink(yytext());
            }
          case 55: break;
          case 28: 
            { Matcher match = Pattern.compile("(#.*)(include)(.*)<(.*)>").matcher(yytext());
        if (match.matches()) {
            out.write(match.group(1));
            writeSymbol(match.group(2), CxxConsts.kwd, yyline);
            out.write(match.group(3));
            out.write("&lt;");
            String path = match.group(4);
            out.write(Util.breadcrumbPath(urlPrefix + "path=", path));
            out.write("&gt;");
        }
            }
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
