/* The following code was generated by JFlex 1.6.1 */

/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2015, 2016, Oracle and/or its affiliates. All rights reserved.
 */

/*
 * Cross reference a Golang file
 */

package org.opensolaris.opengrok.analysis.golang;
import org.opensolaris.opengrok.analysis.JFlexXref;
import org.opensolaris.opengrok.web.Util;

/**
 * @author Patrick Lundquist
 */


public class GolangXref extends JFlexXref {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;
  public static final int SCOMMENT = 6;
  public static final int QSTRING = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\0\1\1\1\2\22\0\1\1\1\10\1\36"+
    "\1\0\2\10\1\43\1\5\2\0\1\37\1\35\1\10\1\6\1\13"+
    "\1\12\1\32\11\7\1\46\1\10\1\40\1\10\1\41\1\10\1\47"+
    "\1\30\1\33\1\31\1\23\1\34\1\26\1\14\1\20\1\25\2\4"+
    "\1\22\1\21\1\4\1\15\1\27\2\4\1\45\1\16\3\4\1\17"+
    "\2\4\1\0\1\42\2\0\1\11\1\0\1\30\1\33\1\31\1\23"+
    "\1\34\1\26\1\14\1\20\1\25\2\4\1\22\1\21\1\4\1\15"+
    "\1\27\2\4\1\45\1\16\3\4\1\17\2\4\3\0\1\10\261\0"+
    "\2\24\115\0\1\44\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ufe90\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\2\3\1\4\1\5\1\6\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\5\1\1\13\2\1"+
    "\1\2\2\14\1\15\1\1\1\6\2\0\1\16\1\17"+
    "\14\0\1\20\1\21\1\22\1\0\1\23\1\6\1\0"+
    "\2\6\14\0\1\2\1\6\6\0\1\24\1\25\17\0"+
    "\1\25\3\0\1\26\2\0\1\27\4\0\1\25\5\0"+
    "\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\310\0\u0140\0\310\0\u0168\0\u0190\0\u01b8\0\310\0\u01e0"+
    "\0\310\0\310\0\u0208\0\u0230\0\u0258\0\u0280\0\u02a8\0\u02d0"+
    "\0\u02f8\0\u0320\0\u0348\0\u0370\0\310\0\u0398\0\u03c0\0\u03e8"+
    "\0\u0410\0\u0438\0\310\0\310\0\u0460\0\u0488\0\u04b0\0\u0208"+
    "\0\u04d8\0\u0500\0\u0528\0\u0230\0\u0550\0\u0578\0\u05a0\0\u05c8"+
    "\0\310\0\310\0\310\0\u05f0\0\310\0\u0618\0\u0640\0\u0640"+
    "\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708\0\u0730\0\u0758\0\u0780"+
    "\0\u07a8\0\u07d0\0\u07f8\0\u0820\0\u0848\0\310\0\u0870\0\u0898"+
    "\0\u08c0\0\u08e8\0\u0910\0\u0938\0\u0960\0\u0988\0\u0208\0\u09b0"+
    "\0\u09d8\0\u0a00\0\u0a28\0\u0a50\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0"+
    "\0\u0b18\0\u0b40\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08\0\u0c30"+
    "\0\u0c58\0\u0c80\0\u0a78\0\u0ca8\0\u0cd0\0\310\0\u0cf8\0\u0d20"+
    "\0\u0d48\0\u0d70\0\310\0\u0d98\0\u0dc0\0\u0de8\0\u0e10\0\u0e38"+
    "\0\u0e38";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\6\1\14"+
    "\1\6\1\12\1\15\1\6\10\12\1\6\5\12\1\16"+
    "\2\12\1\6\1\17\1\6\1\20\1\21\1\6\1\22"+
    "\1\6\1\12\3\6\1\7\1\10\1\11\1\23\1\6"+
    "\2\24\1\6\1\24\1\25\1\24\4\23\1\26\3\23"+
    "\1\6\1\23\1\27\3\23\1\24\2\23\1\6\1\30"+
    "\1\6\1\20\1\21\1\31\1\22\1\6\1\23\3\6"+
    "\1\7\1\10\1\11\1\23\1\6\2\24\1\6\1\24"+
    "\1\25\1\24\4\23\1\26\3\23\1\6\1\23\1\27"+
    "\3\23\1\24\2\23\2\6\1\32\1\20\1\21\1\6"+
    "\1\22\1\6\1\23\3\6\1\33\1\34\1\35\1\23"+
    "\1\6\2\24\1\6\1\24\1\25\1\24\4\23\1\26"+
    "\3\23\1\6\1\23\1\27\3\23\1\24\2\23\3\6"+
    "\1\20\1\21\1\6\1\22\1\6\1\23\3\6\1\7"+
    "\1\10\1\11\1\23\1\36\2\24\1\6\1\24\1\25"+
    "\1\24\4\23\1\26\3\23\1\6\1\23\1\27\3\23"+
    "\1\24\2\23\3\6\1\20\1\21\1\37\1\22\1\6"+
    "\1\23\2\6\51\0\1\7\1\10\1\11\47\0\1\11"+
    "\50\0\2\12\1\0\1\12\1\0\1\12\2\0\10\12"+
    "\1\0\10\12\10\0\1\12\11\0\1\14\1\0\1\40"+
    "\1\0\1\41\16\0\1\14\1\0\1\42\25\0\1\43"+
    "\24\0\1\44\17\0\1\14\1\0\1\40\1\0\1\41"+
    "\3\0\1\45\12\0\1\14\1\0\1\42\17\0\1\46"+
    "\5\0\1\47\1\0\10\46\1\0\5\46\1\0\2\46"+
    "\10\0\1\46\6\0\1\50\1\0\2\50\1\0\1\50"+
    "\1\51\1\52\10\50\1\0\10\50\10\0\1\50\1\0"+
    "\1\53\4\0\1\54\1\0\2\54\1\0\1\54\1\0"+
    "\11\54\1\0\10\54\10\0\1\54\1\0\1\53\4\0"+
    "\1\55\7\0\10\55\1\0\5\55\1\0\2\55\10\0"+
    "\1\55\6\0\1\50\1\0\2\50\1\0\1\50\1\51"+
    "\1\52\2\50\1\56\5\50\1\0\10\50\10\0\1\50"+
    "\1\0\1\53\4\0\1\50\1\0\2\50\1\0\1\50"+
    "\1\51\1\52\2\50\1\57\5\50\1\0\10\50\10\0"+
    "\1\50\1\0\1\53\1\0\1\60\104\0\1\61\3\0"+
    "\1\62\17\0\1\63\36\0\1\33\1\34\1\35\47\0"+
    "\1\35\45\0\1\64\53\0\1\65\34\0\1\62\14\0"+
    "\1\40\1\0\1\40\20\0\1\40\1\0\1\42\22\0"+
    "\1\66\22\0\1\66\23\0\1\67\1\70\22\0\1\70"+
    "\2\0\1\67\21\0\1\71\13\0\1\71\2\0\1\71"+
    "\1\0\5\71\17\0\1\46\1\0\2\46\1\0\1\46"+
    "\1\72\1\73\10\46\1\0\10\46\10\0\1\46\6\0"+
    "\1\74\7\0\10\74\1\0\5\74\1\0\2\74\10\0"+
    "\1\74\6\0\1\75\7\0\10\75\1\0\5\75\1\0"+
    "\2\75\10\0\1\75\6\0\1\50\1\0\2\50\1\0"+
    "\1\50\1\51\1\52\1\76\1\50\1\77\1\50\1\100"+
    "\2\50\1\101\1\0\2\50\1\102\5\50\10\0\1\50"+
    "\1\0\1\53\4\0\1\103\1\0\2\103\1\0\1\103"+
    "\1\0\11\103\1\0\10\103\10\0\1\103\6\0\1\55"+
    "\1\0\2\55\1\0\1\55\1\51\11\55\1\0\10\55"+
    "\10\0\1\55\6\0\1\50\1\0\2\50\1\0\1\50"+
    "\1\51\1\52\2\50\1\104\5\50\1\0\10\50\10\0"+
    "\1\50\1\0\1\53\4\0\1\50\1\0\2\50\1\0"+
    "\1\50\1\51\1\52\10\50\1\0\2\50\1\105\5\50"+
    "\10\0\1\50\1\0\1\53\1\0\1\60\34\0\1\106"+
    "\12\0\1\64\3\0\1\106\51\0\1\66\22\0\1\66"+
    "\1\0\1\42\22\0\1\70\22\0\1\70\24\0\1\71"+
    "\13\0\1\71\2\0\1\71\1\0\4\71\1\107\17\0"+
    "\1\110\7\0\10\110\1\0\5\110\1\0\2\110\10\0"+
    "\1\110\6\0\1\46\1\0\2\46\1\0\1\46\1\72"+
    "\1\73\1\111\1\46\1\112\1\46\1\113\2\46\1\114"+
    "\1\0\2\46\1\115\5\46\10\0\1\46\6\0\1\74"+
    "\1\0\2\74\1\0\1\74\1\72\11\74\1\0\10\74"+
    "\10\0\1\74\6\0\1\116\1\0\1\75\1\116\1\0"+
    "\1\75\1\0\1\75\10\116\1\0\10\116\10\0\1\116"+
    "\6\0\1\50\1\0\2\50\1\0\1\50\1\51\1\52"+
    "\1\50\1\117\6\50\1\0\10\50\10\0\1\50\1\0"+
    "\1\53\4\0\1\50\1\0\2\50\1\0\1\50\1\51"+
    "\1\52\3\50\1\120\4\50\1\0\10\50\10\0\1\50"+
    "\1\0\1\53\4\0\1\50\1\0\2\50\1\0\1\50"+
    "\1\51\1\52\2\50\1\121\5\50\1\0\10\50\10\0"+
    "\1\50\1\0\1\53\4\0\1\50\1\0\2\50\1\0"+
    "\1\50\1\51\1\52\10\50\1\122\1\123\7\50\10\0"+
    "\1\50\1\0\1\53\4\0\1\50\1\0\2\50\1\0"+
    "\1\50\1\51\1\52\10\50\1\0\3\50\1\124\4\50"+
    "\10\0\1\50\1\0\1\53\4\0\1\103\1\0\2\103"+
    "\1\0\1\103\1\0\1\125\10\103\1\0\10\103\10\0"+
    "\1\103\6\0\1\50\1\0\2\50\1\0\1\50\1\51"+
    "\1\52\10\50\1\0\2\50\1\126\5\50\10\0\1\50"+
    "\1\0\1\53\4\0\1\50\1\0\2\50\1\0\1\50"+
    "\1\51\1\52\10\50\1\0\10\50\10\0\1\50\1\127"+
    "\1\53\6\0\1\67\1\71\13\0\1\71\2\0\1\71"+
    "\1\0\4\71\1\107\1\67\16\0\1\130\1\0\1\110"+
    "\1\130\1\0\1\110\1\0\1\110\10\130\1\0\10\130"+
    "\10\0\1\130\6\0\1\46\1\0\2\46\1\0\1\46"+
    "\1\72\1\73\1\46\1\131\6\46\1\0\10\46\10\0"+
    "\1\46\6\0\1\46\1\0\2\46\1\0\1\46\1\72"+
    "\1\73\3\46\1\132\4\46\1\0\10\46\10\0\1\46"+
    "\6\0\1\46\1\0\2\46\1\0\1\46\1\72\1\73"+
    "\2\46\1\133\5\46\1\0\10\46\10\0\1\46\6\0"+
    "\1\46\1\0\2\46\1\0\1\46\1\72\1\73\10\46"+
    "\1\134\1\135\7\46\10\0\1\46\6\0\1\46\1\0"+
    "\2\46\1\0\1\46\1\72\1\73\10\46\1\0\3\46"+
    "\1\136\4\46\10\0\1\46\6\0\1\116\1\0\1\75"+
    "\1\116\1\0\1\75\1\51\1\75\10\116\1\0\10\116"+
    "\10\0\1\116\6\0\1\50\1\0\2\50\1\0\1\50"+
    "\1\51\1\52\2\50\1\117\5\50\1\0\10\50\10\0"+
    "\1\50\1\0\1\53\4\0\1\50\1\0\2\50\1\0"+
    "\1\50\1\51\1\52\5\50\1\137\2\50\1\0\10\50"+
    "\10\0\1\50\1\0\1\53\26\0\1\140\25\0\1\50"+
    "\1\0\2\50\1\0\1\50\1\51\1\52\10\50\1\0"+
    "\1\50\1\141\6\50\10\0\1\50\1\0\1\53\4\0"+
    "\1\50\1\0\2\50\1\0\1\50\1\51\1\52\2\50"+
    "\1\142\5\50\1\0\10\50\10\0\1\50\1\0\1\53"+
    "\4\0\1\143\1\0\2\143\1\0\1\143\1\0\11\143"+
    "\1\0\10\143\10\0\1\143\6\0\1\50\1\0\2\50"+
    "\1\0\1\50\1\51\1\52\10\50\1\0\10\50\7\0"+
    "\1\144\1\105\1\127\1\53\12\0\1\145\41\0\1\130"+
    "\1\0\1\110\1\130\1\0\1\110\1\72\1\110\10\130"+
    "\1\0\10\130\4\0\1\146\3\0\1\130\6\0\1\46"+
    "\1\0\2\46\1\0\1\46\1\72\1\73\10\46\1\0"+
    "\10\46\4\0\1\146\3\0\1\46\6\0\1\46\1\0"+
    "\2\46\1\0\1\46\1\72\1\73\2\46\1\131\5\46"+
    "\1\0\10\46\10\0\1\46\6\0\1\46\1\0\2\46"+
    "\1\0\1\46\1\72\1\73\5\46\1\147\2\46\1\0"+
    "\10\46\10\0\1\46\30\0\1\150\25\0\1\46\1\0"+
    "\2\46\1\0\1\46\1\72\1\73\10\46\1\0\1\46"+
    "\1\151\6\46\10\0\1\46\6\0\1\46\1\0\2\46"+
    "\1\0\1\46\1\72\1\73\2\46\1\152\5\46\1\0"+
    "\10\46\10\0\1\46\6\0\1\50\1\0\2\50\1\0"+
    "\1\50\1\51\1\52\6\50\1\117\1\50\1\0\10\50"+
    "\10\0\1\50\1\0\1\53\26\0\1\153\25\0\1\50"+
    "\1\0\2\50\1\0\1\50\1\51\1\52\10\50\1\0"+
    "\1\50\1\117\6\50\10\0\1\50\1\0\1\53\4\0"+
    "\1\50\1\0\2\50\1\0\1\50\1\51\1\52\10\50"+
    "\1\0\4\50\1\154\3\50\10\0\1\50\1\0\1\53"+
    "\46\0\1\127\13\0\1\155\41\0\1\46\1\0\2\46"+
    "\1\0\1\46\1\72\1\73\6\46\1\131\1\46\1\0"+
    "\10\46\4\0\1\146\3\0\1\46\30\0\1\156\25\0"+
    "\1\46\1\0\2\46\1\0\1\46\1\72\1\73\10\46"+
    "\1\0\1\46\1\131\6\46\10\0\1\46\6\0\1\46"+
    "\1\0\2\46\1\0\1\46\1\72\1\73\10\46\1\0"+
    "\4\46\1\157\3\46\10\0\1\46\6\0\1\50\1\0"+
    "\2\50\1\0\1\50\1\51\1\52\4\50\1\117\3\50"+
    "\1\0\10\50\10\0\1\50\1\0\1\53\4\0\1\160"+
    "\1\0\16\160\1\0\11\160\1\0\1\160\2\0\2\160"+
    "\1\0\3\160\41\0\1\146\12\0\1\46\1\0\2\46"+
    "\1\0\1\46\1\72\1\73\4\46\1\131\3\46\1\0"+
    "\10\46\10\0\1\46\6\0\1\161\1\0\1\160\1\161"+
    "\2\160\1\161\1\160\10\161\1\0\10\161\1\160\1\0"+
    "\1\160\2\0\2\160\1\0\1\161\2\160";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3680];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\2\1\1\11\1\1\1\11\3\1\1\11"+
    "\1\1\2\11\12\1\1\11\3\1\2\0\2\11\14\0"+
    "\3\11\1\0\1\11\1\1\1\0\2\1\14\0\1\11"+
    "\1\1\6\0\2\1\17\0\1\1\3\0\1\1\2\0"+
    "\1\11\4\0\1\11\5\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  // TODO move this into an include file when bug #16053 is fixed
  @Override
  protected int getLineNumber() { return yyline; }
  @Override
  protected void setLineNumber(int x) { yyline = x; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public GolangXref(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 200) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { writeUnicodeChar(yycharat(0));
            }
          case 25: break;
          case 2: 
            { out.write(yytext());
            }
          case 26: break;
          case 3: 
            { startNewLine();
            }
          case 27: break;
          case 4: 
            { String id = yytext();
        writeSymbol(id, Consts.kwd, yyline);
            }
          case 28: break;
          case 5: 
            { yybegin(QSTRING); out.write("<span class=\"s\">\'");
            }
          case 29: break;
          case 6: 
            { out.write("<span class=\"n\">"); out.write(yytext()); out.write("</span>");
            }
          case 30: break;
          case 7: 
            { yybegin(STRING); out.write("<span class=\"s\">\"");
            }
          case 31: break;
          case 8: 
            { out.write( "&lt;");
            }
          case 32: break;
          case 9: 
            { out.write( "&gt;");
            }
          case 33: break;
          case 10: 
            { out.write( "&amp;");
            }
          case 34: break;
          case 11: 
            { yybegin(YYINITIAL); out.write("\"</span>");
            }
          case 35: break;
          case 12: 
            { yybegin(YYINITIAL); out.write("</span>"); startNewLine();
            }
          case 36: break;
          case 13: 
            { yybegin(YYINITIAL); out.write("'</span>");
            }
          case 37: break;
          case 14: 
            { yybegin(SCOMMENT); out.write("<span class=\"c\">//");
            }
          case 38: break;
          case 15: 
            { yybegin(COMMENT); out.write("<span class=\"c\">/*");
            }
          case 39: break;
          case 16: 
            { out.write("\\\"");
            }
          case 40: break;
          case 17: 
            { out.write("\\\\");
            }
          case 41: break;
          case 18: 
            { yybegin(YYINITIAL); out.write("*/</span>");
            }
          case 42: break;
          case 19: 
            { out.write("\\\'");
            }
          case 43: break;
          case 20: 
            { out.write(Util.breadcrumbPath(urlPrefix + "path=", yytext(), '/'));
            }
          case 44: break;
          case 21: 
            { String path = yytext();
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
            }
          case 45: break;
          case 22: 
            { writeEMailAddress(yytext());
            }
          case 46: break;
          case 23: 
            { out.write("&lt;");
    String path = yytext();
    path = path.substring(1, path.length() - 1);
    out.write("<a href=\""+urlPrefix+"path=");
    out.write(path);
    appendProject();
    out.write("\">");
    out.write(path);
    out.write("</a>");
    out.write("&gt;");
            }
          case 47: break;
          case 24: 
            { appendLink(yytext());
            }
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
