/* The following code was generated by JFlex 1.6.1 */

/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").  
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2016, Oracle and/or its affiliates. All rights reserved.
 */

/*
 * Cross reference a Pascal file
 */

package org.opensolaris.opengrok.analysis.pascal;
import org.opensolaris.opengrok.analysis.JFlexXref;
import java.io.IOException;
import java.io.Writer;
import java.io.Reader;
import org.opensolaris.opengrok.web.Util;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/myworld/github/OpenGrok/src/org/opensolaris/opengrok/analysis/pascal/PascalXref.lex</tt>
 */
public class PascalXref extends JFlexXref {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;
  public static final int SCOMMENT = 6;
  public static final int QSTRING = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\0\1\1\1\2\22\0\1\1\1\6\1\45"+
    "\1\53\2\6\1\52\1\46\2\53\1\6\1\37\1\6\1\10\1\11"+
    "\1\34\1\35\11\5\1\54\1\42\1\43\1\6\1\44\1\6\1\55"+
    "\1\13\1\36\1\27\1\33\1\20\1\31\1\41\1\32\1\23\2\4"+
    "\1\26\1\25\1\30\1\17\1\12\1\4\1\16\1\15\1\21\1\40"+
    "\2\4\1\24\2\4\1\53\1\50\2\53\1\7\1\53\1\13\1\36"+
    "\1\27\1\33\1\20\1\31\1\41\1\32\1\23\2\4\1\26\1\25"+
    "\1\30\1\17\1\12\1\4\1\16\1\15\1\21\1\40\2\4\1\24"+
    "\2\4\1\47\1\53\1\51\1\6\261\0\2\22\115\0\1\14\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ufe90\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\2\3\1\4\1\5\3\4\1\5"+
    "\1\4\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\5\4\1\7\1\15\1\4\1\16\1\2\2\17\1\20"+
    "\1\4\1\21\2\0\1\5\1\21\1\22\1\0\1\21"+
    "\13\0\1\23\1\24\1\0\1\25\2\5\1\0\1\26"+
    "\1\5\1\21\17\0\1\2\1\5\1\0\1\21\23\0"+
    "\1\27\3\0\2\30\13\0\2\31\3\0\1\31\1\0"+
    "\1\32\11\0\1\33\11\0\1\34\13\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\u0114\0\u0142"+
    "\0\346\0\u0170\0\u019e\0\346\0\u01cc\0\u01fa\0\u0228\0\u0256"+
    "\0\346\0\u0284\0\346\0\346\0\346\0\346\0\346\0\u02b2"+
    "\0\u02e0\0\u030e\0\u033c\0\u036a\0\346\0\u0398\0\u03c6\0\346"+
    "\0\u03f4\0\u0422\0\346\0\u0450\0\u047e\0\u0170\0\u04ac\0\u04da"+
    "\0\u0508\0\u0536\0\346\0\u0564\0\u0592\0\u05c0\0\u05ee\0\u02b2"+
    "\0\u061c\0\u064a\0\u0678\0\u02e0\0\u06a6\0\u06d4\0\u0702\0\u0730"+
    "\0\346\0\346\0\u075e\0\346\0\u078c\0\u07ba\0\u07e8\0\u0170"+
    "\0\u0816\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\u0958"+
    "\0\u0986\0\u09b4\0\u09e2\0\u0a10\0\u0a3e\0\u0a6c\0\u0a9a\0\u0ac8"+
    "\0\u0af6\0\346\0\u0b24\0\u0b52\0\u0b80\0\u0bae\0\u0bdc\0\u0c0a"+
    "\0\u0c38\0\u0c66\0\u0c94\0\u0cc2\0\u0cf0\0\u0d1e\0\u0d4c\0\u0d7a"+
    "\0\u0da8\0\u0dd6\0\u0e04\0\u0e32\0\u0e60\0\u0e8e\0\u0ebc\0\u0eea"+
    "\0\u0f18\0\u0f46\0\u0f74\0\u0fa2\0\346\0\u0170\0\u0fd0\0\u0ffe"+
    "\0\u102c\0\u105a\0\u1088\0\u10b6\0\u10e4\0\u1112\0\u1140\0\u116e"+
    "\0\u119c\0\346\0\u02b2\0\u11ca\0\u11f8\0\u1226\0\u0e32\0\u1254"+
    "\0\u0f46\0\u1282\0\u12b0\0\u12de\0\u130c\0\u133a\0\u1368\0\u1396"+
    "\0\u13c4\0\u13f2\0\346\0\u1420\0\u144e\0\u147c\0\u14aa\0\u14d8"+
    "\0\u1506\0\u1534\0\u1562\0\u1590\0\u1534\0\u15be\0\u15ec\0\u161a"+
    "\0\u1648\0\u1676\0\u16a4\0\u16d2\0\u1700\0\u172e\0\u175c\0\u178a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\12"+
    "\2\14\2\12\1\6\3\12\1\15\1\12\1\6\11\12"+
    "\1\16\1\17\1\20\1\14\2\12\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\2\14\1\27\3\14\1\6\1\7"+
    "\1\10\1\11\1\30\1\31\1\14\3\31\2\30\1\6"+
    "\5\30\1\6\6\30\1\32\1\33\1\30\1\34\1\31"+
    "\1\30\1\14\2\30\1\14\1\35\1\23\1\36\2\14"+
    "\1\37\1\14\1\27\3\14\1\6\1\7\1\10\1\11"+
    "\1\30\1\31\1\14\3\31\2\30\1\6\5\30\1\6"+
    "\6\30\1\32\1\33\1\30\1\34\1\31\1\30\1\14"+
    "\2\30\1\14\1\35\1\23\4\14\1\40\1\27\3\14"+
    "\1\6\1\41\1\42\1\43\1\30\1\31\1\14\3\31"+
    "\2\30\1\6\5\30\1\6\6\30\1\32\1\33\1\30"+
    "\1\34\1\31\1\30\1\14\2\30\1\14\1\35\1\23"+
    "\5\14\1\27\3\14\1\6\1\7\1\10\1\11\1\30"+
    "\1\31\1\14\3\31\2\30\1\6\5\30\1\6\6\30"+
    "\1\32\1\33\1\30\1\34\1\31\1\30\1\14\2\30"+
    "\1\14\1\35\1\23\1\14\1\44\1\14\1\45\1\14"+
    "\1\27\3\14\57\0\1\7\1\10\1\11\55\0\1\11"+
    "\56\0\2\46\1\0\1\46\2\0\2\46\1\0\5\46"+
    "\1\0\11\46\1\0\2\46\1\0\2\46\21\0\1\13"+
    "\3\0\1\47\6\0\1\50\5\0\1\51\2\0\1\51"+
    "\1\0\1\51\1\0\1\13\2\0\1\51\21\0\2\46"+
    "\1\0\1\46\2\0\2\46\1\0\5\46\1\0\5\46"+
    "\1\52\3\46\1\0\2\46\1\0\2\46\50\0\1\53"+
    "\26\0\1\13\3\0\1\47\6\0\1\50\3\0\1\54"+
    "\1\0\1\51\2\0\1\51\1\0\1\51\1\0\1\13"+
    "\2\0\1\51\21\0\2\46\1\0\1\46\2\0\2\46"+
    "\1\0\3\46\1\55\1\46\1\0\11\46\1\0\2\46"+
    "\1\0\2\46\20\0\1\56\5\0\2\56\1\0\5\56"+
    "\1\0\11\56\1\57\1\0\1\56\1\0\2\56\20\0"+
    "\2\60\1\0\2\60\1\61\2\60\1\0\5\60\1\0"+
    "\11\60\1\62\2\60\1\0\2\60\13\0\1\63\4\0"+
    "\2\64\1\0\5\64\1\0\5\64\1\0\11\64\1\0"+
    "\2\64\1\0\2\64\13\0\1\63\4\0\2\60\1\0"+
    "\2\60\1\61\2\60\1\0\4\60\1\65\1\0\11\60"+
    "\1\62\2\60\1\0\2\60\13\0\1\63\4\0\2\60"+
    "\1\0\2\60\1\61\2\60\1\0\4\60\1\66\1\0"+
    "\11\60\1\62\2\60\1\0\2\60\13\0\1\63\4\0"+
    "\1\67\5\0\2\67\1\0\5\67\1\0\11\67\2\0"+
    "\1\67\1\0\2\67\15\0\1\70\121\0\1\71\2\0"+
    "\1\72\6\0\1\41\1\42\1\43\55\0\1\43\53\0"+
    "\1\73\122\0\1\74\1\0\1\72\12\0\1\75\27\0"+
    "\1\75\25\0\1\76\2\0\1\77\24\0\1\76\1\0"+
    "\1\77\44\0\1\51\2\0\1\51\1\0\1\51\4\0"+
    "\1\51\21\0\2\46\1\0\1\46\2\0\2\46\1\0"+
    "\5\46\1\0\10\46\1\100\1\0\2\46\1\0\2\46"+
    "\21\0\1\101\5\0\1\101\4\0\1\101\6\0\1\101"+
    "\1\0\1\101\1\0\1\101\1\0\2\101\23\0\2\46"+
    "\1\0\1\46\2\0\2\46\1\0\5\46\1\0\11\46"+
    "\1\0\2\46\1\0\1\46\1\102\20\0\2\56\1\0"+
    "\2\56\1\103\2\56\1\0\5\56\1\0\11\56\1\104"+
    "\2\56\1\0\2\56\20\0\1\105\5\0\2\105\1\0"+
    "\5\105\1\0\11\105\2\0\1\105\1\0\2\105\20\0"+
    "\2\60\1\0\2\60\1\61\1\106\1\60\1\0\4\60"+
    "\1\107\1\110\1\111\1\112\2\60\1\113\2\60\1\114"+
    "\1\115\1\62\2\60\1\0\2\60\13\0\1\63\4\0"+
    "\1\116\5\0\2\116\1\0\5\116\1\0\11\116\2\0"+
    "\1\116\1\0\2\116\20\0\2\117\1\0\5\117\1\0"+
    "\5\117\1\0\11\117\1\0\2\117\1\0\2\117\20\0"+
    "\2\60\1\0\2\60\1\61\1\120\1\60\1\0\5\60"+
    "\1\0\11\60\1\62\2\60\1\0\2\60\13\0\1\63"+
    "\4\0\2\60\1\0\2\60\1\61\2\60\1\0\4\60"+
    "\1\121\1\0\11\60\1\62\2\60\1\0\2\60\13\0"+
    "\1\63\4\0\2\67\1\0\5\67\1\0\5\67\1\0"+
    "\11\67\1\62\2\67\1\0\2\67\15\0\1\70\43\0"+
    "\1\122\11\0\1\73\44\0\1\122\14\0\1\75\12\0"+
    "\1\50\5\0\1\51\2\0\1\51\1\0\1\51\1\0"+
    "\1\75\2\0\1\51\22\0\1\76\20\0\1\51\2\0"+
    "\1\51\1\0\1\51\1\0\1\76\2\0\1\51\22\0"+
    "\1\76\27\0\1\76\25\0\1\101\5\0\1\101\4\0"+
    "\1\123\5\0\1\51\1\101\1\0\1\101\1\0\1\101"+
    "\1\0\2\101\1\0\1\51\21\0\2\46\1\0\1\46"+
    "\2\0\2\46\1\0\5\46\1\124\1\125\10\46\1\0"+
    "\2\46\1\0\2\46\20\0\2\56\1\0\2\56\1\103"+
    "\1\126\1\56\1\0\4\56\1\127\1\130\1\131\1\132"+
    "\2\56\1\133\2\56\1\134\1\135\1\104\2\56\1\0"+
    "\2\56\20\0\1\136\5\0\2\136\1\0\5\136\1\0"+
    "\11\136\2\0\1\136\1\0\2\136\20\0\2\105\1\0"+
    "\5\105\1\0\5\105\1\0\11\105\1\104\2\105\1\0"+
    "\2\105\20\0\2\60\1\0\2\60\1\61\1\60\1\137"+
    "\1\0\1\60\1\140\3\60\1\0\11\60\1\62\2\60"+
    "\1\0\2\60\13\0\1\63\4\0\2\60\1\0\2\60"+
    "\1\61\2\60\1\0\5\60\1\0\1\60\1\141\7\60"+
    "\1\62\2\60\1\0\2\60\13\0\1\63\30\0\1\142"+
    "\31\0\2\60\1\0\2\60\1\61\2\60\1\0\5\60"+
    "\1\0\5\60\1\143\3\60\1\62\2\60\1\0\2\60"+
    "\13\0\1\63\4\0\2\60\1\0\2\60\1\61\2\60"+
    "\1\0\5\60\1\0\2\60\1\144\6\60\1\62\2\60"+
    "\1\0\2\60\13\0\1\63\4\0\2\60\1\0\2\60"+
    "\1\61\2\60\1\0\2\60\1\145\2\60\1\0\11\60"+
    "\1\62\2\60\1\0\2\60\13\0\1\63\4\0\2\60"+
    "\1\0\2\60\1\61\2\60\1\0\4\60\1\146\1\0"+
    "\11\60\1\62\2\60\1\0\2\60\13\0\1\63\4\0"+
    "\2\60\1\0\2\60\1\61\2\60\1\0\5\60\1\147"+
    "\1\150\10\60\1\62\2\60\1\0\2\60\13\0\1\63"+
    "\4\0\2\151\1\0\3\116\2\151\1\0\5\151\1\0"+
    "\11\151\1\0\2\151\1\0\2\151\20\0\2\117\1\0"+
    "\2\117\1\152\2\117\1\0\5\117\1\0\11\117\1\0"+
    "\2\117\1\0\2\117\20\0\2\60\1\0\2\60\1\61"+
    "\2\60\1\0\5\60\1\0\11\60\1\62\2\60\1\0"+
    "\2\60\12\0\1\153\1\63\4\0\2\60\1\0\2\60"+
    "\1\61\1\154\1\60\1\0\5\60\1\0\11\60\1\62"+
    "\2\60\1\0\2\60\13\0\1\63\5\0\1\101\2\0"+
    "\1\77\2\0\1\101\4\0\1\123\5\0\1\51\1\101"+
    "\1\0\1\101\1\0\1\101\1\0\2\101\1\77\1\51"+
    "\45\0\1\155\31\0\2\46\1\0\1\46\2\0\2\46"+
    "\1\0\5\46\1\0\5\46\1\156\3\46\1\0\2\46"+
    "\1\0\2\46\20\0\2\56\1\0\2\56\1\103\1\56"+
    "\1\157\1\0\1\56\1\160\3\56\1\0\11\56\1\104"+
    "\2\56\1\0\2\56\20\0\2\56\1\0\2\56\1\103"+
    "\2\56\1\0\5\56\1\0\1\56\1\161\7\56\1\104"+
    "\2\56\1\0\2\56\44\0\1\162\31\0\2\56\1\0"+
    "\2\56\1\103\2\56\1\0\5\56\1\0\5\56\1\163"+
    "\3\56\1\104\2\56\1\0\2\56\20\0\2\56\1\0"+
    "\2\56\1\103\2\56\1\0\5\56\1\0\2\56\1\164"+
    "\6\56\1\104\2\56\1\0\2\56\20\0\2\56\1\0"+
    "\2\56\1\103\2\56\1\0\2\56\1\165\2\56\1\0"+
    "\11\56\1\104\2\56\1\0\2\56\20\0\2\56\1\0"+
    "\2\56\1\103\2\56\1\0\4\56\1\166\1\0\11\56"+
    "\1\104\2\56\1\0\2\56\20\0\2\56\1\0\2\56"+
    "\1\103\2\56\1\0\5\56\1\167\1\170\10\56\1\104"+
    "\2\56\1\0\2\56\20\0\2\171\1\0\3\136\2\171"+
    "\1\0\5\171\1\0\11\171\1\0\2\171\1\0\2\171"+
    "\20\0\2\60\1\0\2\60\1\61\2\60\1\172\1\173"+
    "\3\60\1\174\1\0\11\60\1\62\2\60\1\0\2\60"+
    "\13\0\1\63\4\0\2\60\1\0\2\60\1\61\2\60"+
    "\1\0\2\60\1\175\2\60\1\0\11\60\1\62\2\60"+
    "\1\0\2\60\13\0\1\63\4\0\2\60\1\0\2\60"+
    "\1\61\2\60\1\0\4\60\1\173\1\0\11\60\1\62"+
    "\2\60\1\0\2\60\13\0\1\63\22\0\2\172\36\0"+
    "\2\60\1\0\2\60\1\61\2\60\1\0\5\60\1\172"+
    "\1\173\10\60\1\62\2\60\1\0\2\60\13\0\1\63"+
    "\4\0\2\60\1\0\2\60\1\61\2\60\1\0\5\60"+
    "\1\0\3\60\1\173\5\60\1\62\2\60\1\0\2\60"+
    "\13\0\1\63\4\0\2\60\1\0\2\60\1\61\2\60"+
    "\1\0\5\60\1\0\5\60\1\176\3\60\1\62\2\60"+
    "\1\0\2\60\13\0\1\63\4\0\2\60\1\0\2\60"+
    "\1\61\2\60\1\0\5\60\1\0\2\60\1\177\6\60"+
    "\1\62\2\60\1\0\2\60\13\0\1\63\31\0\1\200"+
    "\30\0\2\60\1\0\2\60\1\61\2\60\1\0\5\60"+
    "\1\0\6\60\1\176\2\60\1\62\2\60\1\0\2\60"+
    "\13\0\1\63\4\0\2\151\1\0\3\116\2\151\1\0"+
    "\5\151\1\0\11\151\1\62\2\151\1\0\2\151\20\0"+
    "\2\201\1\0\5\201\1\0\5\201\1\0\11\201\1\0"+
    "\2\201\1\0\2\201\50\0\1\202\25\0\2\60\1\0"+
    "\2\60\1\61\2\60\1\203\1\120\4\60\1\0\11\60"+
    "\1\62\2\60\1\0\2\60\12\0\1\153\1\63\4\0"+
    "\2\56\1\0\2\56\1\103\2\56\1\204\1\205\3\56"+
    "\1\206\1\0\11\56\1\104\2\56\1\0\2\56\20\0"+
    "\2\56\1\0\2\56\1\103\2\56\1\0\2\56\1\207"+
    "\2\56\1\0\11\56\1\104\2\56\1\0\2\56\20\0"+
    "\2\56\1\0\2\56\1\103\2\56\1\0\4\56\1\205"+
    "\1\0\11\56\1\104\2\56\1\0\2\56\36\0\2\204"+
    "\36\0\2\56\1\0\2\56\1\103\2\56\1\0\5\56"+
    "\1\204\1\205\10\56\1\104\2\56\1\0\2\56\20\0"+
    "\2\56\1\0\2\56\1\103\2\56\1\0\5\56\1\0"+
    "\3\56\1\205\5\56\1\104\2\56\1\0\2\56\20\0"+
    "\2\56\1\0\2\56\1\103\2\56\1\0\5\56\1\0"+
    "\5\56\1\210\3\56\1\104\2\56\1\0\2\56\20\0"+
    "\2\56\1\0\2\56\1\103\2\56\1\0\5\56\1\0"+
    "\2\56\1\211\6\56\1\104\2\56\1\0\2\56\45\0"+
    "\1\212\30\0\2\56\1\0\2\56\1\103\2\56\1\0"+
    "\5\56\1\0\6\56\1\210\2\56\1\104\2\56\1\0"+
    "\2\56\20\0\2\171\1\0\3\136\2\171\1\0\5\171"+
    "\1\0\11\171\1\104\2\171\1\0\2\171\2\0\1\213"+
    "\15\0\2\60\1\0\2\60\1\61\2\60\1\0\5\60"+
    "\1\0\4\60\1\214\4\60\1\62\2\60\1\0\2\60"+
    "\13\0\1\63\4\0\2\60\1\0\2\60\1\61\1\215"+
    "\1\60\1\0\5\60\1\0\11\60\1\62\2\60\1\0"+
    "\2\60\13\0\1\63\4\0\2\60\1\0\2\60\1\61"+
    "\2\60\1\0\5\60\1\0\6\60\1\173\2\60\1\62"+
    "\2\60\1\0\2\60\13\0\1\63\31\0\1\172\60\0"+
    "\1\216\75\0\1\153\45\0\1\213\15\0\2\56\1\0"+
    "\2\56\1\103\2\56\1\0\5\56\1\0\11\56\1\104"+
    "\2\56\1\0\2\56\2\0\1\213\15\0\2\56\1\0"+
    "\2\56\1\103\2\56\1\0\5\56\1\0\4\56\1\217"+
    "\4\56\1\104\2\56\1\0\2\56\20\0\2\56\1\0"+
    "\2\56\1\103\1\220\1\56\1\0\5\56\1\0\11\56"+
    "\1\104\2\56\1\0\2\56\20\0\2\56\1\0\2\56"+
    "\1\103\2\56\1\0\5\56\1\0\6\56\1\205\2\56"+
    "\1\104\2\56\1\0\2\56\20\0\2\56\1\0\2\56"+
    "\1\103\2\56\1\0\5\56\1\0\3\56\1\205\5\56"+
    "\1\104\2\56\1\0\2\56\2\0\1\213\42\0\1\204"+
    "\30\0\2\60\1\0\2\60\1\61\2\60\1\0\5\60"+
    "\1\0\7\60\1\173\1\60\1\62\2\60\1\0\2\60"+
    "\13\0\1\63\4\0\2\60\1\0\2\60\1\61\2\60"+
    "\1\172\1\173\2\60\1\221\1\60\1\0\11\60\1\62"+
    "\2\60\1\0\2\60\13\0\1\63\4\0\10\222\1\0"+
    "\5\222\1\0\20\222\5\0\1\222\1\0\1\222\1\0"+
    "\2\222\4\0\2\56\1\0\2\56\1\103\2\56\1\0"+
    "\5\56\1\0\7\56\1\205\1\56\1\104\2\56\1\0"+
    "\2\56\20\0\2\56\1\0\2\56\1\103\2\56\1\204"+
    "\1\205\2\56\1\223\1\56\1\0\11\56\1\104\2\56"+
    "\1\0\2\56\20\0\2\60\1\0\2\60\1\61\2\60"+
    "\1\0\1\60\1\224\3\60\1\0\11\60\1\62\2\60"+
    "\1\0\2\60\13\0\1\63\4\0\2\225\4\222\2\225"+
    "\1\0\5\225\1\0\14\225\1\222\2\225\1\222\5\0"+
    "\1\222\1\0\1\222\1\0\2\222\4\0\2\56\1\0"+
    "\2\56\1\103\2\56\1\0\1\56\1\226\3\56\1\0"+
    "\11\56\1\104\2\56\1\0\2\56\20\0\2\60\1\0"+
    "\2\60\1\61\2\60\1\0\4\60\1\227\1\0\11\60"+
    "\1\62\2\60\1\0\2\60\13\0\1\63\4\0\2\56"+
    "\1\0\2\56\1\103\2\56\1\0\4\56\1\230\1\0"+
    "\11\56\1\104\2\56\1\0\2\56\20\0\2\60\1\0"+
    "\2\60\1\61\2\60\1\0\5\60\1\231\1\232\10\60"+
    "\1\62\2\60\1\0\2\60\13\0\1\63\4\0\2\56"+
    "\1\0\2\56\1\103\2\56\1\0\5\56\1\233\1\234"+
    "\10\56\1\104\2\56\1\0\2\56\34\0\1\235\41\0"+
    "\2\60\1\0\2\60\1\61\2\60\1\0\3\60\1\236"+
    "\1\60\1\0\11\60\1\62\2\60\1\0\2\60\13\0"+
    "\1\63\20\0\1\237\41\0\2\56\1\0\2\56\1\103"+
    "\2\56\1\0\3\56\1\240\1\56\1\0\11\56\1\104"+
    "\2\56\1\0\2\56\30\0\2\172\44\0\2\60\1\0"+
    "\2\60\1\61\2\60\1\172\1\173\4\60\1\0\11\60"+
    "\1\62\2\60\1\0\2\60\13\0\1\63\14\0\2\204"+
    "\44\0\2\56\1\0\2\56\1\103\2\56\1\204\1\205"+
    "\4\56\1\0\11\56\1\104\2\56\1\0\2\56\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6072];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\2\1\1\11\2\1\1\11\4\1\1\11"+
    "\1\1\5\11\5\1\1\11\2\1\1\11\2\1\1\11"+
    "\3\1\2\0\2\1\1\11\1\0\1\1\13\0\2\11"+
    "\1\0\1\11\2\1\1\0\3\1\17\0\1\11\1\1"+
    "\1\0\1\1\23\0\1\1\3\0\1\11\1\1\13\0"+
    "\1\11\1\1\3\0\1\1\1\0\1\1\11\0\1\11"+
    "\11\0\1\1\13\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  /* Must match WhiteSpace regex */
  private final static String WHITE_SPACE = "[ \t\f\r]+";

  // TODO move this into an include file when bug #16053 is fixed
  @Override
  protected int getLineNumber() { return yyline; }
  @Override
  protected void setLineNumber(int x) { yyline = x; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PascalXref(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 212) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { writeUnicodeChar(yycharat(0));
            }
          case 29: break;
          case 2: 
            { out.write(yytext());
            }
          case 30: break;
          case 3: 
            { startNewLine();
            }
          case 31: break;
          case 4: 
            { out.write(yycharat(0));
            }
          case 32: break;
          case 5: 
            { out.write("<span class=\"n\">"); out.write(yytext()); out.write("</span>");
            }
          case 33: break;
          case 6: 
            { endScope(); writeUnicodeChar(yycharat(0));
            }
          case 34: break;
          case 7: 
            { out.write( "&lt;");
            }
          case 35: break;
          case 8: 
            { out.write( "&gt;");
            }
          case 36: break;
          case 9: 
            { yybegin(STRING);out.write("<span class=\"s\">\"");
            }
          case 37: break;
          case 10: 
            { yybegin(QSTRING);out.write("<span class=\"s\">\'");
            }
          case 38: break;
          case 11: 
            { yybegin(COMMENT);out.write("<span class=\"c\">{");
            }
          case 39: break;
          case 12: 
            { out.write( "&amp;");
            }
          case 40: break;
          case 13: 
            { yybegin(YYINITIAL); out.write("\"</span>");
            }
          case 41: break;
          case 14: 
            { yybegin(YYINITIAL); out.write("}</span>");
            }
          case 42: break;
          case 15: 
            { yybegin(YYINITIAL); out.write("</span>");
    startNewLine();
            }
          case 43: break;
          case 16: 
            { yybegin(YYINITIAL); out.write("'</span>");
            }
          case 44: break;
          case 17: 
            { String id = yytext();
    writeSymbol(id, Consts.kwd, yyline);
            }
          case 45: break;
          case 18: 
            { yybegin(SCOMMENT);out.write("<span class=\"c\">//");
            }
          case 46: break;
          case 19: 
            { out.write("\\\"");
            }
          case 47: break;
          case 20: 
            { out.write("\\\\");
            }
          case 48: break;
          case 21: 
            { out.write("\\\'");
            }
          case 49: break;
          case 22: 
            { decScope(); out.write(yytext());
            }
          case 50: break;
          case 23: 
            { out.write(Util.breadcrumbPath(urlPrefix+"path=",yytext(),'/'));
            }
          case 51: break;
          case 24: 
            { incScope(); out.write(yytext());
            }
          case 52: break;
          case 25: 
            { String path = yytext();
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
            }
          case 53: break;
          case 26: 
            { writeEMailAddress(yytext());
            }
          case 54: break;
          case 27: 
            { out.write("&lt;");
        String path = yytext();
        path = path.substring(1, path.length() - 1);
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
        out.write("&gt;");
            }
          case 55: break;
          case 28: 
            { appendLink(yytext());
            }
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
